services:
  - type: web
    name: portfolio-site
    runtime: static
    rootDir: .
    buildCommand: npm install && set NODE_ENV=production && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_OPTIONS
        value: "--max_old_space_size=2048"
      - key: VITE_SKIP_SSR_CHECKS
        value: "true"
      - key: VITE_DISABLE_ESLINT_PLUGIN
        value: "true"
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html