services:
  - type: web
    name: portfolio-site
    env: node
    region: oregon # Free tier region
    plan: free # Explicitly specify free tier
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 